### PR TITLE
fix: handle scan error

### PR DESCRIPTION
**Pull request by alexandear**
See https://github.com/matoous/godox/pull/11#issuecomment-2562101816

### CODE REVIEW

**Review by matoous — APPROVED** [review]

**Comment by matoous** [comment]
Thank you!

**Comment by mrwormhole** [comment]
hey @matoous do you know when is the next release v1.0.1? thanks so much for this fix @alexandear

**Comment by matoous** [comment]
Will draft one, thanks for pinging me.

**Comment by matoous** [comment]
@mrwormhole here: https://github.com/matoous/godox/releases/tag/v1.1.0

**Pull request merged**
